export type AceScenario = Readonly<{
  id: string;
  title: string;
  axis: string;
  requirements: string;
  choices: readonly string[];
  answer: string;
  reason: string;
  domain: "計画と構成" | "環境セットアップ" | "運用の維持" | "アクセスとセキュリティ";
}>;

const scenario = (
  id: string,
  title: string,
  axis: string,
  requirements: string,
  choices: readonly string[],
  answer: string,
  reason: string,
  domain: AceScenario["domain"] = "計画と構成",
): AceScenario => ({ id, title, axis, requirements, choices, answer, reason, domain });

/** 固定した要件に対する判断教材。実サービスの可用性、性能、料金の測定ではない。 */
export const AceScenarios: readonly AceScenario[] = [
  scenario(
    "platform-vm",
    "OSと独自ドライバを制御するAI基盤",
    "platform",
    "OS、ドライバ、独自プロセスをVM単位で管理する。Kubernetesは不要。",
    ["gce", "gke", "vertex-ai"],
    "gce",
    "Compute EngineでVMを制御する。OS保守とスケール設計も利用者が担う。",
  ),
  scenario(
    "platform-kubernetes",
    "コンテナ化した分散学習を運用する",
    "platform",
    "既存のKubernetes運用、コンテナ配置、ノードプールを再利用する。",
    ["gce", "gke", "vertex-ai"],
    "gke",
    "GKEはKubernetesによるコンテナの配置と運用に対応する。容量確保は別に設計する。",
  ),
  scenario(
    "platform-managed",
    "管理された学習ジョブを選ぶ",
    "platform",
    "独自VM/クラスタの保守を避け、管理されたML学習ジョブを使う。",
    ["gce", "gke", "vertex-ai"],
    "vertex-ai",
    "Vertex AIの管理されたML基盤を選ぶ。現公式文書のAgent Platform名称も参照する。",
  ),
  scenario(
    "accelerator-custom",
    "独自CUDA演算を含むモデル",
    "accelerator",
    "既存CUDAライブラリとTPU未対応の独自演算が必要。",
    ["cpu", "gpu", "tpu"],
    "gpu",
    "対応GPUとCUDA環境を検討する。単純にGPUが常に速いという判断ではない。",
  ),
  scenario(
    "accelerator-matrix",
    "XLA対応の大規模行列計算",
    "accelerator",
    "TPU向けに最適化・検証済みのモデルを使い、安定したshape、大きなbatchで行列演算を行う。",
    ["cpu", "gpu", "tpu"],
    "tpu",
    "TPUを候補にする。演算の対応、shape、batchとデータ供給を確認して実測する。",
  ),
  scenario(
    "capacity-spot",
    "中断可能な学習の費用を抑える",
    "capacity",
    "checkpointから再開でき、終了時刻保証を要しない中断可能な処理。",
    ["spot", "reservation", "dws-flex"],
    "spot",
    "Spotの中断と容量非保証を受け入れる。checkpointと再試行が必要。",
  ),
  scenario(
    "capacity-reserved",
    "予定した時刻のVM容量を確保する",
    "capacity",
    "特定の対応VM構成を予定時刻に使う。割引購入だけでは容量を確保できない。",
    ["spot", "reservation", "committed-discount"],
    "reservation",
    "対応する予約で容量を確保する。予約の対象、地域、使用条件と費用を確認する。",
  ),
  scenario(
    "capacity-flex",
    "待ち行列で短期間のGPU容量を要求する",
    "capacity",
    "開始まで待てる。対応GPUの有限期間ジョブを一括で開始したい。",
    ["spot", "reservation", "dws-flex"],
    "dws-flex",
    "Dynamic Workload SchedulerのFlex-startを検討する。対応構成と実行期間の制約を確認する。",
  ),
  scenario(
    "orchestrator-kubernetes",
    "Kubernetesで学習コンテナを配置する",
    "orchestrator",
    "KubernetesのPod、Job、ノード管理を使用する。",
    ["gke", "slurm", "cluster-toolkit"],
    "gke",
    "GKEでKubernetesを運用する。DWSは容量提供の軸でありschedulerの代用ではない。",
  ),
  scenario(
    "orchestrator-slurm",
    "HPCのジョブ待ち行列を使う",
    "orchestrator",
    "既存HPC利用者がSlurm形式のbatch job、queue、node allocationを必要とする。",
    ["gke", "slurm", "cluster-toolkit"],
    "slurm",
    "Slurmをschedulerにする。クラスタ構築、容量調達、監視は別の関心事。",
  ),
  scenario(
    "orchestrator-blueprint",
    "複数VMのクラスタを構築する",
    "provisioning",
    "再利用するblueprintから計算クラスタを構築したい。ジョブのscheduler自体は別に選ぶ。",
    ["gke", "slurm", "cluster-toolkit"],
    "cluster-toolkit",
    "Cluster Toolkitはクラスタ構築のblueprintを提供する。ジョブschedulerではない。",
  ),
  scenario(
    "runtime-managed",
    "agentの実行基盤を管理してもらう",
    "runtime",
    "agentのdeploy、scale、運用を管理された実行基盤へ委ねる。",
    ["agent-runtime", "workbench", "workstations"],
    "agent-runtime",
    "Vertex AI Agent Engine（現Agent Runtime）を検討する。notebookやIDEと役割を分ける。",
  ),
  scenario(
    "notebook-custom",
    "VMをカスタマイズするnotebook",
    "development",
    "VM型notebookのライブラリ、ネットワーク、実行SAを制御する。",
    ["workbench", "colab-enterprise", "bigquery-notebook", "workstations"],
    "workbench",
    "Workbenchを検討する。notebook VMと開発IDEのWorkstationsは異なる。",
  ),
  scenario(
    "notebook-collaboration",
    "共同編集する管理型notebook",
    "development",
    "ブラウザ上の共同編集と管理されたnotebook実行環境が必要。",
    ["workbench", "colab-enterprise", "bigquery-notebook", "workstations"],
    "colab-enterprise",
    "Colab Enterpriseの共同作業と管理されたruntimeを検討する。",
  ),
  scenario(
    "notebook-warehouse",
    "BigQueryの分析からnotebookへ進む",
    "development",
    "BigQueryの分析画面でSQLとPython notebookを使う。汎用開発IDEは不要。",
    ["workbench", "colab-enterprise", "bigquery-notebook", "workstations"],
    "bigquery-notebook",
    "BigQueryのnotebook連携を使う。実行runtimeとデータ閲覧権限を分けて確認する。",
  ),
  scenario(
    "development-ide",
    "統一した開発IDEを提供する",
    "development",
    "チームへ管理されたIDE、image、persistent storage、idle timeoutを配布する。",
    ["workbench", "colab-enterprise", "workstations"],
    "workstations",
    "Cloud Workstationsの開発環境を使う。Workstations clusterはGKE clusterとは異なる。",
    "環境セットアップ",
  ),
  scenario(
    "assist-cloud",
    "クラウド構成と障害の調査を支援する",
    "assistance",
    "Google Cloudの構成を踏まえて調査・IaC案を得て、人間が根拠と影響を検証する。",
    ["gemini-cloud-assist", "gemini-cli", "active-assist", "service-health"],
    "gemini-cloud-assist",
    "Cloud Assistの調査支援を使う。提案は権限、地域、費用と実データで検証する。",
    "運用の維持",
  ),
  scenario(
    "assist-terminal",
    "ターミナルでコード作業を支援する",
    "assistance",
    "開発者がterminalでコードの説明と変更案を得たい。",
    ["gemini-cloud-assist", "gemini-cli", "active-assist", "cloud-hub"],
    "gemini-cli",
    "Gemini CLIの開発支援を検討する。教材では外部AI、任意コード、shellを実行しない。",
    "環境セットアップ",
  ),
  scenario(
    "assist-recommendation",
    "費用や権限の推奨を検討する",
    "assistance",
    "利用状況から生成された費用・権限のrecommendationを確認し、適用か却下を判断する。",
    ["gemini-cloud-assist", "active-assist", "cloud-hub", "service-health"],
    "active-assist",
    "Active Assistのinsightとrecommendationを検討する。推奨の適用前に影響を確認する。",
    "運用の維持",
  ),
  scenario(
    "assist-overview",
    "health・費用・quotaを集約して見る",
    "assistance",
    "複数の運用指標、incident、maintenance、費用とquotaを一か所で確認する。",
    ["cloud-hub", "service-health", "trace", "profiler"],
    "cloud-hub",
    "Cloud Hubは運用情報を集約する入口。詳細な原因分析は各診断ツールへ進む。",
    "運用の維持",
  ),
  scenario(
    "assist-incident",
    "Google側の障害影響を確認する",
    "assistance",
    "自分のprojectに関連するGoogle Cloud側のservice incidentを確認する。",
    ["cloud-hub", "service-health", "trace", "profiler"],
    "service-health",
    "Personalized Service Healthで関連incidentを確認する。アプリ内のコード障害を自動修復するものではない。",
    "運用の維持",
  ),
  scenario(
    "diagnose-request",
    "分散リクエストの遅延箇所を探す",
    "diagnostics",
    "複数サービスにまたがるrequestとspanのlatencyを追う。",
    ["trace", "profiler", "query-insights", "service-health"],
    "trace",
    "Traceでspan間の時間と依存を調べる。コードのCPU使用率はProfilerの観点。",
    "運用の維持",
  ),
  scenario(
    "diagnose-code",
    "コード内のCPU・メモリ負荷を調べる",
    "diagnostics",
    "特定プロセスの関数別CPUやmemory割当を分析する。",
    ["trace", "profiler", "query-insights", "service-health"],
    "profiler",
    "ProfilerでコードのCPU/memoryを分析する。分散requestやSQL planとは対象が異なる。",
    "運用の維持",
  ),
  scenario(
    "diagnose-sql",
    "遅いSQLの実行計画を確認する",
    "diagnostics",
    "Cloud SQLの遅いquery、実行計画、負荷を調査する。",
    ["trace", "profiler", "query-insights", "service-health"],
    "query-insights",
    "Query Insightsを使う。index advisorなどはengineとeditionの対応条件を確認する。",
    "運用の維持",
  ),
  scenario(
    "iac-state",
    "HCLとplanでクラウド構成を管理する",
    "iac",
    "Google CloudのリソースをHCL、state、plan、applyで管理する。",
    ["terraform", "config-connector", "helm", "fabric-fast"],
    "terraform",
    "Terraformを使う。stateの機密性、lockとplanの変更確認が必要。",
  ),
  scenario(
    "iac-kubernetes",
    "Kubernetes APIからクラウド資源を管理する",
    "iac",
    "KubernetesのCRDとcontrollerでGoogle Cloudリソースを管理する。",
    ["terraform", "config-connector", "helm", "fabric-fast"],
    "config-connector",
    "Config Connectorを使う。controllerのIAMと管理対象の重複を確認する。",
  ),
  scenario(
    "iac-package",
    "Kubernetesアプリのchartを配布する",
    "iac",
    "Kubernetes workloadのtemplateとpackageを再利用する。",
    ["terraform", "config-connector", "helm", "fabric-fast"],
    "helm",
    "Helm chartを使う。Config Syncのhelm template描画はHelm release lifecycle全体ではない。",
  ),
  scenario(
    "iac-foundation",
    "組織のlanding zoneを構築する",
    "iac",
    "bootstrap、hierarchy、network、securityの基盤を段階的なTerraform blueprintで構築する。",
    ["terraform", "config-connector", "helm", "fabric-fast"],
    "fabric-fast",
    "Cloud Foundation FabricのFASTを検討する。基盤blueprintでありmanaged APIサービスではない。",
    "環境セットアップ",
  ),
  scenario(
    "security-private",
    "AI開発環境の公開面を減らす",
    "security",
    "社内開発環境をprivate subnetと必要なアクセス経路に限定する。",
    ["private-access", "public-for-everyone", "disable-iam"],
    "private-access",
    "公開面を絞り、IAM、接続経路、Private Google Accessも確認する。",
    "アクセスとセキュリティ",
  ),
  scenario(
    "security-identity",
    "実行SAの権限を設計する",
    "security",
    "教材のruntimeに必要な権限だけを付け、利用者のactAsと実行SAを区別する。",
    ["least-privilege-sa", "owner-for-all", "embedded-key"],
    "least-privilege-sa",
    "専用SAと必要な権限を使い、永続keyを埋め込まない。",
    "アクセスとセキュリティ",
  ),
  scenario(
    "cost-idle",
    "使っていない開発環境の費用を減らす",
    "cost",
    "再開可能なnotebook/IDEが長時間idleになっている。",
    ["idle-timeout", "always-running", "delete-all-data"],
    "idle-timeout",
    "idle timeoutと停止を設定する。停止後もstorageなどの費用は残り得る。",
    "運用の維持",
  ),
  scenario(
    "cost-discount",
    "安定した利用への割引を検討する",
    "cost",
    "対象構成で継続的な利用が見込める。容量予約とは別に支出commitmentを検討する。",
    ["committed-discount", "spot-guarantee", "free-reservation"],
    "committed-discount",
    "commitmentの範囲と期間を検討する。割引が容量確保を保証するとは限らない。",
  ),
  scenario(
    "assist-antigravity",
    "IDEでagentと開発する",
    "assistance",
    "IDEでAI agentに実装・リファクタ・デバッグを支援させる。",
    ["google-antigravity", "active-assist", "service-health"],
    "google-antigravity",
    "Google Antigravityのagent開発支援を検討する。提案と変更は人間が検証する。",
  ),
  scenario(
    "assist-design",
    "アプリ構成を設計canvasで検討する",
    "assistance",
    "設計canvasと自然言語で構成を検討し、承認済みtemplateをcatalogで共有する。",
    ["app-design-center", "service-health", "profiler"],
    "app-design-center",
    "App Design Centerを検討する。構成の権限・費用・deploy先は別に検証する。",
  ),
  scenario(
    "diagnose-database-fleet",
    "複数製品のDB健全性を集約する",
    "diagnostics",
    "複数projectとDB製品のバックアップ・可用性・セキュリティの問題を集約する。",
    ["database-center", "query-insights", "trace"],
    "database-center",
    "Database Centerを使う。集約情報には更新遅延があり、詳細は個々の製品で調べる。",
    "運用の維持",
  ),
  scenario(
    "capacity-calendar",
    "将来の期間にaccelerator容量を予定する",
    "capacity",
    "対応構成のGPU/TPUを将来の特定期間に使い、予約期間の支払いを受け入れる。",
    ["dws-calendar", "spot", "on-demand"],
    "dws-calendar",
    "DWS Calendarで予約を要求する。承認、対象構成と予約期間全体の課金を確認する。",
  ),
  scenario(
    "capacity-on-demand",
    "事前予約なしで利用量に応じて使う",
    "capacity",
    "事前予約をせず、空き容量の範囲で必要なときに利用し、容量保証を求めない。",
    ["on-demand", "dws-calendar", "committed-discount"],
    "on-demand",
    "On-demandを使う。容量保証はなく、DWSの第3のモードではない。",
  ),
  scenario(
    "diagnose-errors",
    "同じアプリ例外をまとめて見る",
    "diagnostics",
    "アプリのstack traceを含む例外をまとめ、発生回数と増加を調査する。",
    ["error-reporting", "profiler", "service-health"],
    "error-reporting",
    "Error Reportingで例外を集約する。resource指標やGoogle側のincidentとは対象が異なる。",
    "運用の維持",
  ),
  scenario(
    "interface-console",
    "GUIで構成と権限を確認する",
    "interface",
    "ブラウザの管理画面からprojectの構成を見て、小規模な手動操作を確認する。",
    ["console", "mobile", "batch-cli"],
    "console",
    "Google Cloud Consoleを使う。選択projectと権限を確認し、変更内容をレビューする。",
    "環境セットアップ",
  ),
  scenario(
    "interface-cloud-shell",
    "ローカル導入なしでCLIを使う",
    "interface",
    "ブラウザから事前設定されたgcloud環境を使い、ローカルPCへの導入を避ける。",
    ["cloud-shell", "mobile", "marketplace"],
    "cloud-shell",
    "Cloud Shellを使う。教材はterminal操作を再現し、実Cloud Shell sessionは作らない。",
    "環境セットアップ",
  ),
  scenario(
    "interface-cli",
    "同じ操作を繰り返し実行する",
    "interface",
    "projectとaccountを明示し、繰り返しの管理操作をコマンドで再現する。",
    ["batch-cli", "mobile", "marketplace"],
    "batch-cli",
    "gcloud CLIと構成を使う。認証、API、IAMと変更対象を確認する。",
    "環境セットアップ",
  ),
  scenario(
    "interface-mobile",
    "外出先で運用状況を確認する",
    "interface",
    "スマートフォンから対応するリソースの状態とalertを確認する。",
    ["mobile", "marketplace", "terraform"],
    "mobile",
    "Google Cloud mobile appを検討する。ブラウザConsoleと全機能が同じとは限らない。",
    "運用の維持",
  ),
  scenario(
    "marketplace-review",
    "事前パッケージされた製品を検討する",
    "selection",
    "事前パッケージのソフトウェアを検討し、provider、license、IAMと費用をレビューする。",
    ["marketplace", "cloud-shell", "service-health"],
    "marketplace",
    "Cloud Marketplaceの製品を検討する。購入・deployは教材の対象外で、審査済みでも権限と契約を確認する。",
  ),
  scenario(
    "placement-catalog",
    "配置前に製品のロケーションを確認する",
    "placement",
    "特定地域で使う製品と構成について、配置前に提供地域・quota・組織制約を確認する。",
    ["availability-check", "all-regions-identical", "discount-guarantee"],
    "availability-check",
    "製品の公式ロケーションと構成条件を確認する。教材の2地域は実可用性カタログではない。",
  ),
  scenario(
    "redundancy-design",
    "広域の障害に備えてデータを設計する",
    "placement",
    "地域障害への耐性とRPO/RTOを満たすデータ製品の複製・復旧設計を選ぶ。",
    ["replication-and-recovery", "single-zone-only", "no-backups"],
    "replication-and-recovery",
    "対応する広域構成と復旧手順を設計し、整合性、遅延、費用、復旧を検証する。region数だけで要件達成とはしない。",
  ),
  scenario(
    "platform-cloud-run",
    "statelessなHTTPコンテナを公開する",
    "platform",
    "標準HTTPコンテナをrequest単位でスケールさせ、VMやKubernetesの保守を避ける。",
    ["cloud-run", "gce", "gke"],
    "cloud-run",
    "Cloud Runを検討する。対応するcontainerと認証、concurrency、timeout、費用を確認する。",
  ),
];

export const findScenario = (id: string): AceScenario | undefined =>
  AceScenarios.find((s) => s.id === id);
