export const ComputeLabPermissions = [
  "compute.instances.setScheduling",
  "compute.instances.osAdminLogin",
  "compute.snapshots.delete",
  "compute.images.create",
  "compute.images.get",
  "compute.images.delete",
  "compute.resourcePolicies.create",
  "compute.resourcePolicies.get",
  "compute.resourcePolicies.list",
  "compute.resourcePolicies.delete",
  "compute.disks.addResourcePolicies",
  "compute.disks.removeResourcePolicies",
  "tpu.nodes.create",
  "tpu.nodes.get",
  "tpu.nodes.list",
  "tpu.nodes.delete",
  "tpu.nodes.update",
  "osconfig.inventories.get",
  "osconfig.inventories.list",
  "osconfig.osPolicyAssignments.create",
  "osconfig.osPolicyAssignments.get",
  "osconfig.osPolicyAssignments.list",
  "osconfig.osPolicyAssignments.update",
  "osconfig.osPolicyAssignments.delete",
] as const;
