export const ObserveMonitoringRead = [
  "monitoring.notificationChannels.get",
  "monitoring.notificationChannels.list",
  "monitoring.metricDescriptors.get",
  "monitoring.metricDescriptors.list",
  "monitoring.metricsScopes.get",
  "monitoring.services.get",
  "monitoring.services.list",
  "monitoring.slos.get",
  "monitoring.slos.list",
] as const;
export const ObserveMonitoringWrite = [
  ...ObserveMonitoringRead,
  "monitoring.notificationChannels.create",
  "monitoring.notificationChannels.update",
  "monitoring.notificationChannels.delete",
  "monitoring.metricDescriptors.create",
  "monitoring.metricDescriptors.delete",
  "monitoring.timeSeries.create",
  "monitoring.metricsScopes.link",
  "monitoring.dashboards.update",
  "monitoring.alertPolicies.update",
  "monitoring.uptimeCheckConfigs.update",
  "monitoring.services.create",
  "monitoring.slos.create",
  "monitoring.slos.update",
  "monitoring.slos.delete",
] as const;
export const ObserveLoggingRead = [
  "logging.buckets.get",
  "logging.buckets.list",
  "logging.views.get",
  "logging.views.list",
  "logging.links.get",
  "logging.links.list",
  "logging.exclusions.get",
  "logging.exclusions.list",
] as const;
export const ObserveLoggingWrite = [
  ...ObserveLoggingRead,
  "logging.buckets.create",
  "logging.buckets.update",
  "logging.buckets.delete",
  "logging.views.create",
  "logging.views.update",
  "logging.views.delete",
  "logging.views.setIamPolicy",
  "logging.links.create",
  "logging.links.delete",
  "logging.exclusions.create",
  "logging.exclusions.update",
  "logging.exclusions.delete",
] as const;
